##########################################################################
#                                                                        #
#  This file is part of Frama-C.                                         #
#                                                                        #
#  Copyright (C) 2007-2021                                               #
#    CEA (Commissariat à l'énergie atomique et aux énergies              #
#         alternatives)                                                  #
#                                                                        #
#  All rights reserved.                                                  #
#  Contact CEA LIST for licensing.                                       #
#                                                                        #
##########################################################################

.PHONY: all modern pdf

all: modern pdf

include ../MakeLaTeXModern

modern: $(FRAMAC_MODERN)
pdf:
	latexmk -silent -pdf release.tex

