[kernel] Parsing callbacks.i (no preprocessing)
[eva] Analyzing a complete application starting at main1
[eva] Computing initial state
[eva] Initial state computed
[eva:initial-state] Values of globals at initialization
  x ∈ {0}
  y ∈ {0}
[eva] computing for function g1 <- main1.
  Called from callbacks.i:27.
[eva] computing for function f <- g1 <- main1.
  Called from callbacks.i:18.
[eva] Recording results for f
[from] Computing for function f
[from] Done for function f
[eva] Done for function f
[eva] Recording results for g1
[from] Computing for function g1
[from] Done for function g1
[eva] Done for function g1
[eva] computing for function g2 <- main1.
  Called from callbacks.i:28.
[eva] computing for function f <- g2 <- main1.
  Called from callbacks.i:23.
[eva] Recording results for f
[from] Computing for function f
[from] Done for function f
[eva] Done for function f
[eva] Recording results for g2
[from] Computing for function g2
[from] Done for function g2
[eva] Done for function g2
[eva] Recording results for main1
[from] Computing for function main1
[from] Done for function main1
[eva] done for function main1
[eva:summary] ====== ANALYSIS SUMMARY ======
  ----------------------------------------------------------------------------
  4 functions analyzed (out of 6): 66% coverage.
  In these functions, 9 statements reached (out of 9): 100% coverage.
  ----------------------------------------------------------------------------
  No errors or warnings raised during the analysis.
  ----------------------------------------------------------------------------
  0 alarms generated by the analysis.
  ----------------------------------------------------------------------------
  No logical properties have been reached by the analysis.
  ----------------------------------------------------------------------------
[from] ====== DISPLAYING CALLWISE DEPENDENCIES ======
[from] call to f at callbacks.i:18 (by g1):
  x FROM p
[from] call to f at callbacks.i:23 (by g2):
  y FROM p
[from] call to g1 at callbacks.i:27 (by main1):
  x FROM \nothing
[from] call to g2 at callbacks.i:28 (by main1):
  y FROM \nothing
[from] entry point:
  x FROM \nothing
  y FROM \nothing
[from] ====== END OF CALLWISE DEPENDENCIES ======
[inout] Out (internal) for function f:
    x; y
[inout] Out (internal) for function g1:
    x
[inout] Out (internal) for function g2:
    y
[inout] Out (internal) for function main1:
    x; y
