/* Generated by Frama-C */
#include "pthread.h"
#include "sched.h"
#include "signal.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "stdlib.h"
#include "time.h"
char *__gen_e_acsl_literal_string;
extern  __attribute__((__FC_BUILTIN__)) int __e_acsl_sound_verdict;

/*@ requires valid_nptr: \valid_read(nptr);
    assigns \result;
    assigns \result \from (indirect: nptr), (indirect: *(nptr + (0 ..)));
 */
int __gen_e_acsl_atoi(char const *nptr);

int a;
char *n = (char *)"134";
/*@ requires valid_nptr: \valid_read(nptr);
    assigns \result;
    assigns \result \from (indirect: nptr), (indirect: *(nptr + (0 ..)));
 */
int __gen_e_acsl_atoi(char const *nptr)
{
  int __retres;
  {
    int __gen_e_acsl_valid_read;
    __e_acsl_store_block((void *)(& nptr),8UL);
    __e_acsl_assert_data_t __gen_e_acsl_assert_data = {.values = (void *)0};
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data,"nptr",
                                 (void *)nptr);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data,
                                   "sizeof(char const)",0,sizeof(char const));
    __gen_e_acsl_valid_read = __e_acsl_valid_read((void *)nptr,
                                                  sizeof(char const),
                                                  (void *)nptr,
                                                  (void *)(& nptr));
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data,
                                 "\\valid_read(nptr)",0,
                                 __gen_e_acsl_valid_read);
    __gen_e_acsl_assert_data.blocking = 1;
    __gen_e_acsl_assert_data.kind = "Precondition";
    __gen_e_acsl_assert_data.pred_txt = "\\valid_read(nptr)";
    __gen_e_acsl_assert_data.file = "FRAMAC_SHARE/libc/stdlib.h";
    __gen_e_acsl_assert_data.fct = "atoi";
    __gen_e_acsl_assert_data.line = 78;
    __gen_e_acsl_assert_data.name = "valid_nptr";
    __e_acsl_assert(__gen_e_acsl_valid_read,& __gen_e_acsl_assert_data);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data);
  }
  __retres = atoi(nptr);
  __e_acsl_delete_block((void *)(& nptr));
  return __retres;
}

void __e_acsl_globals_init(void)
{
  static char __e_acsl_already_run = 0;
  if (! __e_acsl_already_run) {
    __e_acsl_already_run = 1;
    __gen_e_acsl_literal_string = "134";
    __e_acsl_store_block((void *)__gen_e_acsl_literal_string,sizeof("134"));
    __e_acsl_full_init((void *)__gen_e_acsl_literal_string);
    __e_acsl_mark_readonly((void *)__gen_e_acsl_literal_string);
    __e_acsl_store_block((void *)(& n),8UL);
    __e_acsl_full_init((void *)(& n));
  }
  return;
}

void __e_acsl_globals_clean(void)
{
  __e_acsl_delete_block((void *)(& n));
  return;
}

int main(int argc, char **argv)
{
  int __retres;
  __e_acsl_memory_init(& argc,& argv,8UL);
  __e_acsl_globals_init();
  argc = __gen_e_acsl_atoi((char const *)n);
  a = argc;
  __retres = 0;
  __e_acsl_globals_clean();
  __e_acsl_memory_clean();
  return __retres;
}


