##########################################################################
#                                                                        #
#  This file is part of WP plug-in of Frama-C.                           #
#                                                                        #
#  Copyright (C) 2007-2022                                               #
#    CEA (Commissariat a l'energie atomique et aux energies              #
#         alternatives)                                                  #
#                                                                        #
#  you can redistribute it and/or modify it under the terms of the GNU   #
#  Lesser General Public License as published by the Free Software       #
#  Foundation, version 2.1.                                              #
#                                                                        #
#  It is distributed in the hope that it will be useful,                 #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU Lesser General Public License for more details.                   #
#                                                                        #
#  See the GNU Lesser General Public License version 2.1                 #
#  for more details (enclosed in the file licenses/LGPLv2.1).            #
#                                                                        #
##########################################################################

# --------------------------------------------------------------------------
# ---  Why-3 Libraries
# --------------------------------------------------------------------------

## Used in share/why3

WHY3_LIBS_CEA:=	\
 cbits.mlw 	\
 cint.mlw 	\
 cfloat.mlw 	\
 cmath.mlw 	\
 memory.mlw 	\
 qed.mlw 	\
 vset.mlw	\
 vlist.mlw

## Used in share/why3
WHY3_API_LIBS_CEA:= WHY3_LIBS_CEA

# --------------------------------------------------------------------------
# ---  LICENSES
# --------------------------------------------------------------------------

# Resource classes for license header files
# These files are relatives to this directory
WP_SHARE_SRC_CEA_RESOURCES:= \
	wp.driver \
	why3/coq.drv \
	$(addprefix why3/frama_c_wp/,  $(WHY3_LIBS_CEA))

ALL_CEA_RESOURCES+= \
	install.ml \
	Makefile.resources \
	$(WP_SHARE_SRC_CEA_RESOURCES)

##########################################################################
# Local Variables:
# mode: makefile
# End:
