# --------------------------------------------------------------------------
# ---  Packages Definitions for Dome environment                         ---
# --------------------------------------------------------------------------

DOME_DEV_PACKAGES= \
	@babel/core \
	@babel/preset-env \
	@babel/preset-react \
	@babel/plugin-proposal-object-rest-spread \
	electron@^16 \
	electron-builder \
	electron-webpack \
	electron-devtools-installer \
	webpack@^4 \
	babel-loader \
	css-loader@^5 \
	react-hot-loader@^4 \
	@hot-loader/react-dom@^16 \
	@types/react@^16 \
	@types/react-dom@^16 \
	@types/react-virtualized@^9.21.0

DOME_APP_PACKAGES= \
	react@^16 \
	react-dom@^16 \
	source-map-support \
	lodash \
	react-virtualized \
	react-draggable \
	react-fast-compare \
	codemirror

# --------------------------------------------------------------------------
